trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    export NNI_RELEASE=999.$(date -u +%Y%m%d%H%M%S)

- task: Docker@2
  inputs:
    containerRegistry: msraieg-docker
    repository: nnidev/nni-nightly
    command: build
    Dockerfile: '**/Dockerfile'
    arguments: --build-arg NNI_RELEASE=${NNI_RELEASE}
  displayName: Build Docker Image

- task: Docker@2
  inputs:
    containerRegistry: msraieg-docker
    repository: nnidev/nni-nightly
    command: push
  displayName: Push Docker Image
